# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         HTTP-WebTest-Plugin-Sticky
version:      0.01
version_from: lib/HTTP/WebTest/Plugin/Sticky.pm
installdirs:  site
requires:
    HTML::TokeParser:              0
    HTTP::WebTest:                 0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
